# Generated by Django 3.2.5 on 2022-02-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argonaute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boatteam',
            options={'verbose_name': 'boat member'},
        ),
    ]
